/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Classes.Cachorro;
import DAO.CaoDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author limag
 */
public class ConsultarCao extends javax.swing.JFrame {

    /**
     * Creates new form RelGerCao
     */
    
    //met listar
    public void Listar(){
        try{
            CaoDAO dao= new CaoDAO();
            List<Cachorro> listacao = dao.ConsCao();
            
            
       
            DefaultTableModel model = (DefaultTableModel)tabCao.getModel();     
            //int l = model.getRowCount();
            model.setNumRows(0);
            //if(l>0){
               // while(l>0){
                   // (( DefaultTableModel)tabCao.getModel()).removeRow(l-1);
                    //}
            //}
      
            for(Cachorro v :listacao){
              model.addRow(new Object[]{
              v.getId(),
              v.getNome(),
              v.getIdade(),
              v.getRaca(),
              v.getSexo(),
              v.getCor(),
              v.getPorte(),
              v.getCastrado(),
              v.getVermifugado(),
              v.getStatus()
              
            });
                
         }
        } catch (Exception e) {
       
        } 
        
    }
        
    
    public ConsultarCao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabCao = new javax.swing.JTable();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboFiltro = new javax.swing.JComboBox<>();
        jtarg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultar Cães");
        setMinimumSize(new java.awt.Dimension(790, 700));
        setPreferredSize(new java.awt.Dimension(500, 685));
        setResizable(isUndecorated());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabCao.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tabCao.setForeground(new java.awt.Color(73, 81, 129));
        tabCao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Idade", "Raca", "Sexo", "Cor", "Porte", "Castrado", "Vermifugado", "Staus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabCao.setSelectionBackground(new java.awt.Color(73, 81, 129));
        tabCao.setShowGrid(false);
        jScrollPane2.setViewportView(tabCao);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 750, 230));
        getContentPane().add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 30, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/voltar.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 70, 80));

        btVoltar.setContentAreaFilled(false);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 282, 90, 70));

        jLabel3.setText("Consultar por:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        comboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nome", "Sexo", "Castrado" }));
        getContentPane().add(comboFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jtarg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtargKeyReleased(evt);
            }
        });
        getContentPane().add(jtarg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 480, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/relcao.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(790, 600));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 790, 840));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Listar();
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //listando dados
        //Listar(1);
    }//GEN-LAST:event_formWindowOpened

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        voltar();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void jtargKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtargKeyReleased
        
            
        String tipo="";
        
        //String status = null;
        String escolha=comboFiltro.getSelectedItem().toString().trim();
        if(escolha.equals("Id")){
            tipo=" "+"IdCao";
        }
        if(escolha.equals("Nome")){
            tipo=" "+"Nome";
        }
        if(escolha.equals("Sexo")){
            tipo=" "+"Sexo";
            if(escolha.equals("Castrado")){
            tipo=" "+"Castrado";
        }
            String arg=jtarg.getText();
        
        
        
        DefaultTableModel mpl = (DefaultTableModel)tabCao.getModel();
        int l = mpl.getRowCount();
        
        if(l>0){
            while(l>0){
            ((DefaultTableModel) tabCao.getModel()).removeRow(l-1);
            l--;
        }
        }
        
        
       //String arg = jtarg.getText();
        //CaoDAO dao= new CaoDAO();
        
       //ResultSet rs = CaoDAO.ConsCaoFiltro(tipo,arg);
       try{
        CaoDAO dao= new CaoDAO();
        List<Cachorro> listacao  = dao.ConsCaoFiltro(tipo, arg);
        DefaultTableModel mp = (DefaultTableModel)tabCao.getModel();
        mp.setNumRows(0);
        //for(Cachorro v:listacao)
        /*while(rs.next()){
        String Coluna0=rs.getString("idcao").toString().trim();
        String Coluna1=rs.getString("nome").toString().trim();
        String Coluna2=rs.getString("idade").toString().trim();
        String Coluna3=rs.getString("raca").toString().trim();
        String Coluna4=rs.getString("sexo").toString().trim();
        String Coluna5=rs.getString("cor").toString().trim();
        String Coluna6=rs.getString("porte").toString().trim();
        String Coluna7=rs.getString("castrado").toString().trim();
        String Coluna8=rs.getString("vermifugado").toString().trim();
        String Coluna9="";
       if(status.equals("1")){
            Coluna5="Ativo";
        }if(status.equals("0")){
            Coluna5="Inativo";
        mp.addRow(new String[]{Coluna0,Coluna1,Coluna2,Coluna3,Coluna4,Coluna5,Coluna6,Coluna7,Coluna8,Coluna9});
        
        }}*/
        for(Cachorro v :listacao){
            mp.addRow(new Object[]{
                v.getId(),
                v.getNome(),
                v.getIdade(),
                v.getRaca(),
                v.getSexo(),
                v.getCor(),
                v.getPorte(),
                v.getCastrado(),
                v.getVermifugado(),
                v.getStatus()
                    
            });
     
         
        } 
        }catch(Exception e){
                }
        }
    }//GEN-LAST:event_jtargKeyReleased
    public void voltar(){
        new MenuPrincipal().setVisible(true);
        this.dispose(); 
    }
    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarCao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVoltar;
    private javax.swing.JComboBox<String> comboFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jtarg;
    private javax.swing.JTable tabCao;
    // End of variables declaration//GEN-END:variables
}
