/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Marcos Kuhn
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUser = new javax.swing.JLabel();
        User = new javax.swing.JTextField();
        lblSebha = new javax.swing.JLabel();
        Senha = new javax.swing.JPasswordField();
        btEntrar = new javax.swing.JButton();
        checkManter = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setPreferredSize(new java.awt.Dimension(928, 545));
        setResizable(isUndecorated());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUser.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(73, 81, 129));
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icon-user.png"))); // NOI18N
        lblUser.setText("Usuário");
        getContentPane().add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 100, 30));

        User.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        User.setForeground(new java.awt.Color(84, 88, 113));
        User.setBorder(null);
        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });
        getContentPane().add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 200, 30));

        lblSebha.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblSebha.setForeground(new java.awt.Color(73, 81, 129));
        lblSebha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/senha-icon.png"))); // NOI18N
        lblSebha.setText("Senha");
        getContentPane().add(lblSebha, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        Senha.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        Senha.setForeground(new java.awt.Color(84, 88, 113));
        Senha.setBorder(null);
        Senha.setMinimumSize(new java.awt.Dimension(64, 26));
        getContentPane().add(Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 200, 30));

        btEntrar.setContentAreaFilled(false);
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 290, 50));

        checkManter.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        checkManter.setForeground(new java.awt.Color(84, 66, 121));
        checkManter.setText("Manter-me conectado");
        getContentPane().add(checkManter, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Miranda Ong (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 980, 533));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserActionPerformed

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed

        if(User.getText().equals("admin") && Senha.getText().equals("1234")){
            new MenuPrincipal().setVisible(true);
           this.dispose(); 
        } else {
            JOptionPane.showMessageDialog(null, "Usuário ou Senha incorretos", "Dados Incorretos", 0);
            
        }  
          
    }//GEN-LAST:event_btEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Senha;
    private javax.swing.JTextField User;
    private javax.swing.JButton btEntrar;
    private javax.swing.JCheckBox checkManter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSebha;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
