/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Marcos Kuhn
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jdbprincipal = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        mnAnimais = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnCao = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnCadCao = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnAltCao = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnRelCadCao = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mnGato = new javax.swing.JMenu();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnCadGato = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mnAltGato = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        mnRelCadGato = new javax.swing.JMenuItem();
        mnAdotantes = new javax.swing.JMenu();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        mnCadAdotante = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        mnAltAdotante = new javax.swing.JMenuItem();
        mnAltAdo = new javax.swing.JPopupMenu.Separator();
        mnConsulAdo = new javax.swing.JMenuItem();
        mnAdocao = new javax.swing.JMenu();
        jSeparator20 = new javax.swing.JPopupMenu.Separator();
        mnAgenda = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator22 = new javax.swing.JPopupMenu.Separator();
        mnalt = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        mnevento = new javax.swing.JMenuItem();
        jSeparator25 = new javax.swing.JPopupMenu.Separator();
        mnremv = new javax.swing.JMenuItem();
        jSeparator24 = new javax.swing.JPopupMenu.Separator();
        jSeparator21 = new javax.swing.JPopupMenu.Separator();
        menuAdotados = new javax.swing.JMenu();
        relCaes = new javax.swing.JMenuItem();
        jSeparator23 = new javax.swing.JPopupMenu.Separator();
        relGatos = new javax.swing.JMenuItem();
        mnAlmox = new javax.swing.JMenu();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        mnCad = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        mnAlt = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        mnCons = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JPopupMenu.Separator();
        mnRemove = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        mnCadVol = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        mnAltVol = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        mnConsVolutario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator26 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jSeparator27 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator28 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenu();
        mnBtSair = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu Principal");
        setBackground(new java.awt.Color(240, 241, 248));
        setResizable(isUndecorated());

        jdbprincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/tela-menu2.png"))); // NOI18N

        barraMenu.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        barraMenu.setPreferredSize(new java.awt.Dimension(111, 30));

        mnAnimais.setForeground(new java.awt.Color(84, 88, 113));
        mnAnimais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/pet.png"))); // NOI18N
        mnAnimais.setText("Animais");
        mnAnimais.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mnAnimais.add(jSeparator5);

        mnCao.setForeground(new java.awt.Color(84, 88, 113));
        mnCao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/dogue-alemao.png"))); // NOI18N
        mnCao.setText("Cachorro");
        mnCao.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mnCao.add(jSeparator4);

        mnCadCao.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mnCadCao.setForeground(new java.awt.Color(51, 51, 51));
        mnCadCao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/paw-dog.png"))); // NOI18N
        mnCadCao.setText("Cadastrar Cão");
        mnCadCao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mnCadCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadCaoActionPerformed(evt);
            }
        });
        mnCao.add(mnCadCao);
        mnCao.add(jSeparator1);

        mnAltCao.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mnAltCao.setForeground(new java.awt.Color(51, 51, 51));
        mnAltCao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/alterar.png"))); // NOI18N
        mnAltCao.setText("Alterar Cadastro de Cão");
        mnAltCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAltCaoActionPerformed(evt);
            }
        });
        mnCao.add(mnAltCao);
        mnCao.add(jSeparator3);

        mnRelCadCao.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mnRelCadCao.setForeground(new java.awt.Color(51, 51, 51));
        mnRelCadCao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/list.png"))); // NOI18N
        mnRelCadCao.setText("Consultar Cães Cadastrados");
        mnRelCadCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRelCadCaoActionPerformed(evt);
            }
        });
        mnCao.add(mnRelCadCao);

        mnAnimais.add(mnCao);
        mnAnimais.add(jSeparator7);

        mnGato.setForeground(new java.awt.Color(84, 88, 113));
        mnGato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/gato.png"))); // NOI18N
        mnGato.setText("Gato");
        mnGato.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mnGato.add(jSeparator6);

        mnCadGato.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mnCadGato.setForeground(new java.awt.Color(51, 51, 51));
        mnCadGato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/paw-gato.png"))); // NOI18N
        mnCadGato.setText("Cadastrar Gato");
        mnCadGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadGatoActionPerformed(evt);
            }
        });
        mnGato.add(mnCadGato);
        mnGato.add(jSeparator8);

        mnAltGato.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mnAltGato.setForeground(new java.awt.Color(51, 51, 51));
        mnAltGato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/alterar.png"))); // NOI18N
        mnAltGato.setText("Alterar Cadastro de Gato");
        mnAltGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAltGatoActionPerformed(evt);
            }
        });
        mnGato.add(mnAltGato);
        mnGato.add(jSeparator9);

        mnRelCadGato.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mnRelCadGato.setForeground(new java.awt.Color(51, 51, 51));
        mnRelCadGato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/list.png"))); // NOI18N
        mnRelCadGato.setText("Consultar Gatos Cadastrados");
        mnRelCadGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRelCadGatoActionPerformed(evt);
            }
        });
        mnGato.add(mnRelCadGato);

        mnAnimais.add(mnGato);

        barraMenu.add(mnAnimais);

        mnAdotantes.setForeground(new java.awt.Color(84, 88, 113));
        mnAdotantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/group.png"))); // NOI18N
        mnAdotantes.setText("Adotantes");
        mnAdotantes.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mnAdotantes.add(jSeparator10);

        mnCadAdotante.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mnCadAdotante.setForeground(new java.awt.Color(84, 88, 113));
        mnCadAdotante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icon-user.png"))); // NOI18N
        mnCadAdotante.setText("Cadastrar Adotante");
        mnCadAdotante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadAdotanteActionPerformed(evt);
            }
        });
        mnAdotantes.add(mnCadAdotante);
        mnAdotantes.add(jSeparator12);

        mnAltAdotante.setBackground(new java.awt.Color(84, 88, 113));
        mnAltAdotante.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mnAltAdotante.setForeground(new java.awt.Color(84, 88, 113));
        mnAltAdotante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/alterar.png"))); // NOI18N
        mnAltAdotante.setText("Alterar  Cadastro");
        mnAltAdotante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAltAdotanteActionPerformed(evt);
            }
        });
        mnAdotantes.add(mnAltAdotante);
        mnAdotantes.add(mnAltAdo);

        mnConsulAdo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mnConsulAdo.setForeground(new java.awt.Color(84, 88, 113));
        mnConsulAdo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/clipboard.png"))); // NOI18N
        mnConsulAdo.setText("Consultar Adotantes Cadastrados");
        mnConsulAdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsulAdoActionPerformed(evt);
            }
        });
        mnAdotantes.add(mnConsulAdo);

        barraMenu.add(mnAdotantes);

        mnAdocao.setForeground(new java.awt.Color(84, 88, 113));
        mnAdocao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/adotado.png"))); // NOI18N
        mnAdocao.setText("Adoção");
        mnAdocao.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mnAdocao.add(jSeparator20);

        mnAgenda.setForeground(new java.awt.Color(84, 88, 113));
        mnAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/calendar.png"))); // NOI18N
        mnAgenda.setText("Agenda");
        mnAgenda.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem6.setForeground(new java.awt.Color(51, 51, 51));
        jMenuItem6.setText("Agendar Entrevista de Adoção");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnAgenda.add(jMenuItem6);
        mnAgenda.add(jSeparator22);

        mnalt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mnalt.setForeground(new java.awt.Color(51, 51, 51));
        mnalt.setText("Alterar Entrevista");
        mnalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnaltActionPerformed(evt);
            }
        });
        mnAgenda.add(mnalt);
        mnAgenda.add(jSeparator16);

        mnevento.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mnevento.setForeground(new java.awt.Color(51, 51, 51));
        mnevento.setText("Consultar Agenda de Entrevistas");
        mnevento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mneventoActionPerformed(evt);
            }
        });
        mnAgenda.add(mnevento);
        mnAgenda.add(jSeparator25);

        mnremv.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mnremv.setForeground(new java.awt.Color(51, 51, 51));
        mnremv.setText("Remover Entrevista");
        mnAgenda.add(mnremv);
        mnAgenda.add(jSeparator24);

        mnAdocao.add(mnAgenda);
        mnAdocao.add(jSeparator21);

        menuAdotados.setForeground(new java.awt.Color(84, 88, 113));
        menuAdotados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/pet-house.png"))); // NOI18N
        menuAdotados.setText("Animais Adotados");
        menuAdotados.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        relCaes.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        relCaes.setForeground(new java.awt.Color(51, 51, 51));
        relCaes.setText("Relatório de Cães Adotados");
        menuAdotados.add(relCaes);
        menuAdotados.add(jSeparator23);

        relGatos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        relGatos.setForeground(new java.awt.Color(51, 51, 51));
        relGatos.setText("Relatório de Gatos Adotados");
        menuAdotados.add(relGatos);

        mnAdocao.add(menuAdotados);

        barraMenu.add(mnAdocao);

        mnAlmox.setForeground(new java.awt.Color(84, 88, 113));
        mnAlmox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/gift.png"))); // NOI18N
        mnAlmox.setText("Almoxarifado");
        mnAlmox.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mnAlmox.add(jSeparator15);

        mnCad.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mnCad.setForeground(new java.awt.Color(84, 88, 113));
        mnCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/product.png"))); // NOI18N
        mnCad.setText("Cadastrar Item");
        mnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadActionPerformed(evt);
            }
        });
        mnAlmox.add(mnCad);
        mnAlmox.add(jSeparator17);

        mnAlt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mnAlt.setForeground(new java.awt.Color(84, 88, 113));
        mnAlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/product 1.png"))); // NOI18N
        mnAlt.setText("Alterar Item");
        mnAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAltActionPerformed(evt);
            }
        });
        mnAlmox.add(mnAlt);
        mnAlmox.add(jSeparator18);

        mnCons.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mnCons.setForeground(new java.awt.Color(84, 88, 113));
        mnCons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lista.png"))); // NOI18N
        mnCons.setText("Consultar Item");
        mnCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsActionPerformed(evt);
            }
        });
        mnAlmox.add(mnCons);
        mnAlmox.add(jSeparator19);

        mnRemove.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mnRemove.setForeground(new java.awt.Color(84, 88, 113));
        mnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/delete.png"))); // NOI18N
        mnRemove.setText("Remover Item");
        mnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRemoveActionPerformed(evt);
            }
        });
        mnAlmox.add(mnRemove);

        barraMenu.add(mnAlmox);

        jMenu1.setForeground(new java.awt.Color(84, 88, 113));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/group.png"))); // NOI18N
        jMenu1.setText("Voluntários");
        jMenu1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jMenu1.add(jSeparator11);

        mnCadVol.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mnCadVol.setForeground(new java.awt.Color(84, 88, 113));
        mnCadVol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icon-user.png"))); // NOI18N
        mnCadVol.setText("Cadastrar Voluntário");
        mnCadVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadVolActionPerformed(evt);
            }
        });
        jMenu1.add(mnCadVol);
        jMenu1.add(jSeparator13);

        mnAltVol.setBackground(new java.awt.Color(84, 88, 113));
        mnAltVol.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mnAltVol.setForeground(new java.awt.Color(84, 88, 113));
        mnAltVol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/alterar.png"))); // NOI18N
        mnAltVol.setText("Alterar  Voluntário");
        mnAltVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAltVolActionPerformed(evt);
            }
        });
        jMenu1.add(mnAltVol);
        jMenu1.add(jSeparator14);

        mnConsVolutario.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mnConsVolutario.setForeground(new java.awt.Color(84, 88, 113));
        mnConsVolutario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lista.png"))); // NOI18N
        mnConsVolutario.setText("Consultar Cadastro de Voluntário");
        mnConsVolutario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsVolutarioActionPerformed(evt);
            }
        });
        jMenu1.add(mnConsVolutario);

        barraMenu.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(84, 88, 113));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/conversao.png"))); // NOI18N
        jMenu2.setText("Financeiro");
        jMenu2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(84, 88, 113));
        jMenuItem4.setText("Registrar Despesas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);
        jMenu2.add(jSeparator26);

        jMenu3.setForeground(new java.awt.Color(84, 88, 113));
        jMenu3.setText("Relatório de Despesas");
        jMenu3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        jMenu4.setForeground(new java.awt.Color(51, 51, 51));
        jMenu4.setText("Semanal");
        jMenu4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu3.add(jMenu4);
        jMenu3.add(jSeparator27);

        jMenuItem8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem8.setForeground(new java.awt.Color(51, 51, 51));
        jMenuItem8.setText("Mensal");
        jMenu3.add(jMenuItem8);
        jMenu3.add(jSeparator28);

        jMenu5.setForeground(new java.awt.Color(51, 51, 51));
        jMenu5.setText("Anual");
        jMenu5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu3.add(jMenu5);

        jMenu2.add(jMenu3);

        barraMenu.add(jMenu2);

        mnSair.setForeground(new java.awt.Color(84, 88, 113));
        mnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/sair.png"))); // NOI18N
        mnSair.setText("Sair");
        mnSair.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        mnBtSair.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        mnBtSair.setForeground(new java.awt.Color(84, 88, 113));
        mnBtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/sair.png"))); // NOI18N
        mnBtSair.setText("Sair");
        mnBtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBtSairActionPerformed(evt);
            }
        });
        mnSair.add(mnBtSair);

        barraMenu.add(mnSair);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdbprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdbprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void mnBtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBtSairActionPerformed
        sair();
    }//GEN-LAST:event_mnBtSairActionPerformed

    private void mnCadCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadCaoActionPerformed
        new CadCao().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_mnCadCaoActionPerformed

    private void mnAltCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAltCaoActionPerformed
        AlterarCao alt = new AlterarCao();
        alt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnAltCaoActionPerformed

    private void mnRelCadCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelCadCaoActionPerformed
        ConsultarCao consCao = new ConsultarCao();
        consCao.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_mnRelCadCaoActionPerformed

    private void mnCadGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadGatoActionPerformed
         new CadGato().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnCadGatoActionPerformed

    private void mnRelCadGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelCadGatoActionPerformed
        ConsultarGato consGato = new ConsultarGato();
        consGato.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_mnRelCadGatoActionPerformed

    private void mnAltGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAltGatoActionPerformed
         AlterarGato alt = new AlterarGato();
        alt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnAltGatoActionPerformed

    private void mnConsulAdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsulAdoActionPerformed
    new ConsAdotante().setVisible(true);
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_mnConsulAdoActionPerformed

    private void mnCadAdotanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadAdotanteActionPerformed
    new CadAdotante().setVisible(true);  
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_mnCadAdotanteActionPerformed

    private void mnAltAdotanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAltAdotanteActionPerformed
    new AlterarAdotante().setVisible(true);
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_mnAltAdotanteActionPerformed

    private void mnCadVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadVolActionPerformed
    new CadVoluntario().setVisible(true);
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_mnCadVolActionPerformed

    private void mnAltVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAltVolActionPerformed
    new AlterarVoluntario().setVisible(true);
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_mnAltVolActionPerformed

    private void mnConsVolutarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsVolutarioActionPerformed
    new ConsultarVoluntario().setVisible(true);
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_mnConsVolutarioActionPerformed

    private void mnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadActionPerformed
    new CadAlmoxarifado().setVisible(true);
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_mnCadActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new AgendarEntrevista().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void mneventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mneventoActionPerformed
    new ConsultarAgenda().setVisible(true);
    this.dispose();
           // TODO add your handling code here:
    }//GEN-LAST:event_mneventoActionPerformed

    private void mnAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAltActionPerformed
    new AltAlmoxarifado().setVisible(true);
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_mnAltActionPerformed

    private void mnConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsActionPerformed
    new ConsAlmoxarifado().setVisible(true);
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_mnConsActionPerformed

    private void mnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRemoveActionPerformed
    new RemoveItem().setVisible(true);
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_mnRemoveActionPerformed

    private void mnaltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnaltActionPerformed
        new AltAgenda().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnaltActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
new RegGastos().setVisible(true);
this.dispose();

    }//GEN-LAST:event_jMenuItem4ActionPerformed
     public void sair (){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja sair do Menu Principal?", "Saida", JOptionPane.YES_NO_CANCEL_OPTION);
      if (resp == 0){
          dispose ();
          new Login().setVisible(true);
      }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator20;
    private javax.swing.JPopupMenu.Separator jSeparator21;
    private javax.swing.JPopupMenu.Separator jSeparator22;
    private javax.swing.JPopupMenu.Separator jSeparator23;
    private javax.swing.JPopupMenu.Separator jSeparator24;
    private javax.swing.JPopupMenu.Separator jSeparator25;
    private javax.swing.JPopupMenu.Separator jSeparator26;
    private javax.swing.JPopupMenu.Separator jSeparator27;
    private javax.swing.JPopupMenu.Separator jSeparator28;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JLabel jdbprincipal;
    private javax.swing.JMenu menuAdotados;
    private javax.swing.JMenu mnAdocao;
    private javax.swing.JMenu mnAdotantes;
    private javax.swing.JMenu mnAgenda;
    private javax.swing.JMenu mnAlmox;
    private javax.swing.JMenuItem mnAlt;
    private javax.swing.JPopupMenu.Separator mnAltAdo;
    private javax.swing.JMenuItem mnAltAdotante;
    private javax.swing.JMenuItem mnAltCao;
    private javax.swing.JMenuItem mnAltGato;
    private javax.swing.JMenuItem mnAltVol;
    private javax.swing.JMenu mnAnimais;
    private javax.swing.JMenuItem mnBtSair;
    private javax.swing.JMenuItem mnCad;
    private javax.swing.JMenuItem mnCadAdotante;
    private javax.swing.JMenuItem mnCadCao;
    private javax.swing.JMenuItem mnCadGato;
    private javax.swing.JMenuItem mnCadVol;
    private javax.swing.JMenu mnCao;
    private javax.swing.JMenuItem mnCons;
    private javax.swing.JMenuItem mnConsVolutario;
    private javax.swing.JMenuItem mnConsulAdo;
    private javax.swing.JMenu mnGato;
    private javax.swing.JMenuItem mnRelCadCao;
    private javax.swing.JMenuItem mnRelCadGato;
    private javax.swing.JMenuItem mnRemove;
    private javax.swing.JMenu mnSair;
    private javax.swing.JMenuItem mnalt;
    private javax.swing.JMenuItem mnevento;
    private javax.swing.JMenuItem mnremv;
    private javax.swing.JMenuItem relCaes;
    private javax.swing.JMenuItem relGatos;
    // End of variables declaration//GEN-END:variables
}
