/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

/**
 *
 * @author limag
 */
public class RegGastos extends javax.swing.JFrame {

    /**
     * Creates new form Relatóriodegastos
     */
    public RegGastos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        ctipo = new javax.swing.JComboBox<>();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        lblNome = new javax.swing.JLabel();
        lblNome1 = new javax.swing.JLabel();
        lblNome2 = new javax.swing.JLabel();
        lblNome3 = new javax.swing.JLabel();
        lblNome4 = new javax.swing.JLabel();
        ctipo1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Despesas");
        setMinimumSize(new java.awt.Dimension(467, 555));
        setPreferredSize(new java.awt.Dimension(467, 585));
        setResizable(isUndecorated());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 190, 30));

        ctipo.setBackground(new java.awt.Color(49, 12, 93));
        ctipo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ctipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DINHEIRO", "CARTÃO", "CREDIARIO" }));
        getContentPane().add(ctipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 190, 30));

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$#.##,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 190, 30));

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 190, 30));

        lblNome.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(73, 81, 129));
        lblNome.setText("Tipo");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, 30));

        lblNome1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblNome1.setForeground(new java.awt.Color(73, 81, 129));
        lblNome1.setText("Descrição");
        getContentPane().add(lblNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, 30));

        lblNome2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblNome2.setForeground(new java.awt.Color(73, 81, 129));
        lblNome2.setText("Valor");
        getContentPane().add(lblNome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, 30));

        lblNome3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblNome3.setForeground(new java.awt.Color(73, 81, 129));
        lblNome3.setText("Forma Pag");
        getContentPane().add(lblNome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, 30));

        lblNome4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblNome4.setForeground(new java.awt.Color(73, 81, 129));
        lblNome4.setText("Data");
        getContentPane().add(lblNome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, 30));

        ctipo1.setBackground(new java.awt.Color(49, 12, 93));
        ctipo1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ctipo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentação", "Medicamentos", "Despesas fixas", " " }));
        getContentPane().add(ctipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 190, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/voltar 32px.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 70, 40));

        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 120, 60, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/registrardesp.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(467, 570));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        new MenuPrincipal().setVisible(true);
        this.dispose(); 
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegGastos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ctipo;
    private javax.swing.JComboBox<String> ctipo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JLabel lblNome3;
    private javax.swing.JLabel lblNome4;
    // End of variables declaration//GEN-END:variables
}
