/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Classes.Gato;
import javax.swing.JOptionPane;
import DAO.GatoDAO;
import java.util.List;

/**
 *
 * @author limag
 */
public class SalvarAltGato extends javax.swing.JFrame {

    /**
     * Creates new form SalvarAltGato
     */
    public SalvarAltGato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoSexGato = new javax.swing.ButtonGroup();
        GrupoCastradoGato = new javax.swing.ButtonGroup();
        grupoVermGato = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lblNome = new javax.swing.JLabel();
        txtNomeg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblIdade2 = new javax.swing.JLabel();
        txtIdade = new javax.swing.JTextField();
        lblRaca = new javax.swing.JLabel();
        txtRaca = new javax.swing.JTextField();
        lblSexo1 = new javax.swing.JLabel();
        lblCor2 = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        lblCastrado1 = new javax.swing.JLabel();
        lblVermifugado = new javax.swing.JLabel();
        radioSimCas = new javax.swing.JRadioButton();
        radioNaoCas = new javax.swing.JRadioButton();
        radioSimVer = new javax.swing.JRadioButton();
        radioNaoVer = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        comboSexo = new javax.swing.JComboBox<>();
        lblPorte = new javax.swing.JLabel();
        radioAtivo = new javax.swing.JRadioButton();
        radioInativo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Dados");
        setResizable(isUndecorated());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(250, 236, 235));
        lblNome.setText("Nome");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, 30));

        txtNomeg.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtNomeg.setForeground(new java.awt.Color(84, 88, 113));
        txtNomeg.setBorder(null);
        getContentPane().add(txtNomeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 160, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 236, 235));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, -1, 40));

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(255, 229, 255));
        txtId.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtId.setForeground(new java.awt.Color(84, 88, 113));
        txtId.setBorder(null);
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 60, 30));

        lblIdade2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblIdade2.setForeground(new java.awt.Color(250, 236, 235));
        lblIdade2.setText("Idade");
        getContentPane().add(lblIdade2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, 30));

        txtIdade.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtIdade.setForeground(new java.awt.Color(84, 88, 113));
        txtIdade.setBorder(null);
        getContentPane().add(txtIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 60, 30));

        lblRaca.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblRaca.setForeground(new java.awt.Color(250, 236, 235));
        lblRaca.setText("Raça");
        getContentPane().add(lblRaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, 30));

        txtRaca.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtRaca.setForeground(new java.awt.Color(84, 88, 113));
        txtRaca.setBorder(null);
        getContentPane().add(txtRaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 130, 30));

        lblSexo1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblSexo1.setForeground(new java.awt.Color(250, 236, 235));
        lblSexo1.setText("Sexo");
        getContentPane().add(lblSexo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, 30));

        lblCor2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblCor2.setForeground(new java.awt.Color(250, 236, 235));
        lblCor2.setText("Cor");
        getContentPane().add(lblCor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, 30));

        txtCor.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtCor.setForeground(new java.awt.Color(84, 88, 113));
        txtCor.setBorder(null);
        getContentPane().add(txtCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 260, 30));

        lblCastrado1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblCastrado1.setForeground(new java.awt.Color(250, 236, 235));
        lblCastrado1.setText("Castrado");
        getContentPane().add(lblCastrado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, 30));

        lblVermifugado.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblVermifugado.setForeground(new java.awt.Color(250, 236, 235));
        lblVermifugado.setText("Vermifugado");
        getContentPane().add(lblVermifugado, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 120, 30));

        GrupoCastradoGato.add(radioSimCas);
        radioSimCas.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radioSimCas.setForeground(new java.awt.Color(250, 236, 235));
        radioSimCas.setText("Sim");
        getContentPane().add(radioSimCas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, 30));

        GrupoCastradoGato.add(radioNaoCas);
        radioNaoCas.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radioNaoCas.setForeground(new java.awt.Color(250, 236, 235));
        radioNaoCas.setText("Não");
        radioNaoCas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNaoCasActionPerformed(evt);
            }
        });
        getContentPane().add(radioNaoCas, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, 30));

        grupoVermGato.add(radioSimVer);
        radioSimVer.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radioSimVer.setForeground(new java.awt.Color(250, 236, 235));
        radioSimVer.setText("Sim");
        getContentPane().add(radioSimVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, -1, 30));

        grupoVermGato.add(radioNaoVer);
        radioNaoVer.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radioNaoVer.setForeground(new java.awt.Color(250, 236, 235));
        radioNaoVer.setText("Não");
        getContentPane().add(radioNaoVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, -1, 30));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 255));
        jLabel3.setText("___________________________________________________");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 350, -1));

        btSalvar.setContentAreaFilled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 220, 60));

        comboSexo.setBackground(new java.awt.Color(59, 58, 71));
        comboSexo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        comboSexo.setForeground(new java.awt.Color(255, 239, 224));
        comboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Macho", "Fêmea" }));
        comboSexo.setToolTipText("");
        comboSexo.setBorder(null);
        comboSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSexoActionPerformed(evt);
            }
        });
        getContentPane().add(comboSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 120, 30));

        lblPorte.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblPorte.setForeground(new java.awt.Color(250, 236, 235));
        lblPorte.setText("Status");
        getContentPane().add(lblPorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, -1, 30));

        buttonGroup1.add(radioAtivo);
        radioAtivo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radioAtivo.setForeground(new java.awt.Color(250, 236, 235));
        radioAtivo.setText("Ativo");
        getContentPane().add(radioAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, -1, 30));

        buttonGroup1.add(radioInativo);
        radioInativo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radioInativo.setForeground(new java.awt.Color(250, 236, 235));
        radioInativo.setText("Inativo");
        getContentPane().add(radioInativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/altGatotela.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void radioNaoCasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNaoCasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNaoCasActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
         AlterarGato alt = new AlterarGato();
        
        Gato g = new Gato();    
        g.setNome(txtNomeg.getText());
        g.setId(Integer.parseInt(txtId.getText()));
        g.setIdade(Integer.parseInt(txtIdade.getText()));
        g.setRaca(txtRaca.getText());
                   if (radioAtivo.isSelected()){
            g.setStatus("Ativo");
        }else if(radioInativo.isSelected()){
            g.setStatus("Inativo");
        }
        g.setCor(txtCor.getText());
       g.setSexo((String) comboSexo.getSelectedItem());
        if(radioSimCas.isSelected()){
            g.setCastrado("Sim");
        }else if (radioNaoCas.isSelected()){
            g.setCastrado("Nao");
        }
        if(radioSimVer.isSelected()){
            g.setVermifugado("Sim");
        }else if (radioNaoVer.isSelected()){
            g.setVermifugado("Nao");
        }
         
        GatoDAO dao = new GatoDAO();
        dao.alterarGato(g);

        JOptionPane.showMessageDialog(null, "Dados alterados com sucesso.", "Alteração Concluída",1);
        
        alt.setVisible(true);
        this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_btSalvarActionPerformed

    private void comboSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSexoActionPerformed
        selectCombo();        // TODO add your handling code here:
    }//GEN-LAST:event_comboSexoActionPerformed
        public void selectCombo(){
        if(comboSexo.getSelectedIndex()>=1){
            int posLin = comboSexo.getSelectedIndex();
            String valLinCombo = comboSexo.getSelectedItem().toString();
        }}
    public void alterar(Integer id){
        try {
            GatoDAO dao = new GatoDAO();
            List<Gato> listGato = dao.ConsGatoId(id);
            
            for(Gato f : listGato){
                txtId.setText(String.valueOf(f.getId()));
                txtNomeg.setText(f.getNome());
                txtIdade.setText(String.valueOf(f.getIdade()));
                txtRaca.setText(f.getRaca());
                comboSexo.setSelectedItem(String.valueOf(f.getSexo()));
               if (radioAtivo.isSelected()){
            f.setStatus("Ativo");
        }else if(radioInativo.isSelected()){
            f.setStatus("Inativo");
        }
                txtCor.setText(f.getCor());
            
               //f.setPorte((String) comboPorte.getSelectedItem());
              
         
         if(radioSimCas.isSelected()){
            f.setCastrado("Sim");     
        }else if (radioNaoCas.isSelected()){
            f.setCastrado("Nao");
        }
        if(radioSimVer.isSelected()){
            f.setVermifugado("Sim");
        }else if (radioNaoVer.isSelected()){
            f.setVermifugado("Nao");
}
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalvarAltGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalvarAltGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalvarAltGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalvarAltGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalvarAltGato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoCastradoGato;
    private javax.swing.ButtonGroup GrupoSexGato;
    private javax.swing.JButton btSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboSexo;
    private javax.swing.ButtonGroup grupoVermGato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCastrado1;
    private javax.swing.JLabel lblCor2;
    private javax.swing.JLabel lblIdade2;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPorte;
    private javax.swing.JLabel lblRaca;
    private javax.swing.JLabel lblSexo1;
    private javax.swing.JLabel lblVermifugado;
    private javax.swing.JRadioButton radioAtivo;
    private javax.swing.JRadioButton radioInativo;
    private javax.swing.JRadioButton radioNaoCas;
    private javax.swing.JRadioButton radioNaoVer;
    private javax.swing.JRadioButton radioSimCas;
    private javax.swing.JRadioButton radioSimVer;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNomeg;
    private javax.swing.JTextField txtRaca;
    // End of variables declaration//GEN-END:variables
}
