/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Classes.Almoxarifado;
import javax.swing.JOptionPane;
import DAO.AlmxDAO;
/**
 *
 * @author limag
 */
import java.util.List;
public class SalvarAltAlmx extends javax.swing.JFrame {

    /**
     * Creates new form SalvarAltAlmx
     */
    public SalvarAltAlmx() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSalvar = new javax.swing.JButton();
        lblSexo2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        idalm = new javax.swing.JTextField();
        lblSexo3 = new javax.swing.JLabel();
        combocat = new javax.swing.JComboBox<>();
        lblSexo1 = new javax.swing.JLabel();
        qtd = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        btSalvar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btSalvar.setContentAreaFilled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Cadastro de Itens");
        setResizable(isUndecorated());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSexo2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblSexo2.setForeground(new java.awt.Color(73, 81, 129));
        lblSexo2.setText("Nome");
        getContentPane().add(lblSexo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, 30));

        nome.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        nome.setForeground(new java.awt.Color(84, 88, 113));
        nome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(73, 81, 129), 1, true));
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 150, 30));

        idalm.setEditable(false);
        idalm.setBackground(new java.awt.Color(84, 88, 113));
        idalm.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        idalm.setForeground(new java.awt.Color(84, 88, 113));
        idalm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(73, 81, 129), 1, true));
        getContentPane().add(idalm, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 60, 30));

        lblSexo3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblSexo3.setForeground(new java.awt.Color(73, 81, 129));
        lblSexo3.setText("Categoria");
        getContentPane().add(lblSexo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, 30));

        combocat.setBackground(new java.awt.Color(59, 58, 71));
        combocat.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        combocat.setForeground(new java.awt.Color(255, 239, 224));
        combocat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Alimento", "Higiene", "Limpeza", "Medicamento" }));
        combocat.setToolTipText("");
        combocat.setBorder(null);
        combocat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocatActionPerformed(evt);
            }
        });
        getContentPane().add(combocat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 150, 30));

        lblSexo1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblSexo1.setForeground(new java.awt.Color(73, 81, 129));
        lblSexo1.setText("Qtd");
        getContentPane().add(lblSexo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, 30));

        qtd.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        qtd.setForeground(new java.awt.Color(84, 88, 113));
        qtd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(73, 81, 129), 1, true));
        getContentPane().add(qtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 50, 30));

        lblNome.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(73, 81, 129));
        lblNome.setText("Id");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, 50));

        btSalvar1.setContentAreaFilled(false);
        btSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 140, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/altcadaalm.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combocatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocatActionPerformed
        selectCombo();        // TODO add your handling code here:
    }//GEN-LAST:event_combocatActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        //cadastrarProd();        // TODO add your handling code here:
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvar1ActionPerformed
        AltAlmoxarifado alt = new AltAlmoxarifado();
        
        Almoxarifado g = new Almoxarifado();    
        g.setId(Integer.parseInt(idalm.getText()));
        g.setNome(nome.getText());
        
        g.setCat((String) combocat.getSelectedItem());
        g.setQuant(Integer.parseInt(qtd.getText()));
        
         
        AlmxDAO dao = new AlmxDAO();
        dao.alterarProd(g);

        JOptionPane.showMessageDialog(null, "Dados alterados com sucesso.", "Alteração Concluída",1);
        
        alt.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btSalvar1ActionPerformed
public void selectCombo(){
        if(combocat.getSelectedIndex()>=1){
            int posLin = combocat.getSelectedIndex();
            String valLinCombo = combocat.getSelectedItem().toString();
        }
    }
    
    public void alterar(Integer id){
        try {
            AlmxDAO dao = new AlmxDAO();
            List<Almoxarifado> listCao = dao.ConsProdId(id);
            
            for(Almoxarifado f : listCao){
                idalm.setText(String.valueOf(f.getId()));
                nome.setText(f.getNome());
                combocat.setSelectedItem(String.valueOf(f.getCat()));
                qtd.setText(String.valueOf(f.getQuant()));
                
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalvarAltAlmx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalvarAltAlmx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalvarAltAlmx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalvarAltAlmx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalvarAltAlmx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btSalvar1;
    private javax.swing.JComboBox<String> combocat;
    private javax.swing.JTextField idalm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSexo1;
    private javax.swing.JLabel lblSexo2;
    private javax.swing.JLabel lblSexo3;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField qtd;
    // End of variables declaration//GEN-END:variables
}
