/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Marcos Kuhn
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        mnAnimais = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnCao = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnCadCao = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnAltCao = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnRelCadCao = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mnGato = new javax.swing.JMenu();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnCadGato = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mnAltGato = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        mnRelCadGato = new javax.swing.JMenuItem();
        mnSair = new javax.swing.JMenu();
        mnBtSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu Principal");
        setBackground(new java.awt.Color(240, 241, 248));
        setPreferredSize(new java.awt.Dimension(910, 550));
        setResizable(isUndecorated());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/tela-menu2.png"))); // NOI18N

        barraMenu.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        barraMenu.setPreferredSize(new java.awt.Dimension(111, 30));

        mnAnimais.setForeground(new java.awt.Color(84, 88, 113));
        mnAnimais.setText("Animais");
        mnAnimais.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mnAnimais.add(jSeparator5);

        mnCao.setForeground(new java.awt.Color(84, 88, 113));
        mnCao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/dogue-alemao.png"))); // NOI18N
        mnCao.setText("Cachorro");
        mnCao.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mnCao.add(jSeparator4);

        mnCadCao.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mnCadCao.setForeground(new java.awt.Color(51, 51, 51));
        mnCadCao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/paw-dog.png"))); // NOI18N
        mnCadCao.setText("Cadastrar Cão");
        mnCadCao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mnCao.add(mnCadCao);
        mnCao.add(jSeparator1);

        mnAltCao.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mnAltCao.setForeground(new java.awt.Color(51, 51, 51));
        mnAltCao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/alterar.png"))); // NOI18N
        mnAltCao.setText("Alterar Cadastro de Cão");
        mnCao.add(mnAltCao);
        mnCao.add(jSeparator3);

        mnRelCadCao.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mnRelCadCao.setForeground(new java.awt.Color(51, 51, 51));
        mnRelCadCao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/list.png"))); // NOI18N
        mnRelCadCao.setText("Consultar Cães Cadastrados");
        mnCao.add(mnRelCadCao);

        mnAnimais.add(mnCao);
        mnAnimais.add(jSeparator7);

        mnGato.setForeground(new java.awt.Color(84, 88, 113));
        mnGato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/gato.png"))); // NOI18N
        mnGato.setText("Gato");
        mnGato.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mnGato.add(jSeparator6);

        mnCadGato.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mnCadGato.setForeground(new java.awt.Color(51, 51, 51));
        mnCadGato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/paw-gato.png"))); // NOI18N
        mnCadGato.setText("Cadastrar Gato");
        mnGato.add(mnCadGato);
        mnGato.add(jSeparator8);

        mnAltGato.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mnAltGato.setForeground(new java.awt.Color(51, 51, 51));
        mnAltGato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/alterar.png"))); // NOI18N
        mnAltGato.setText("Alterar Cadastro de Gato");
        mnGato.add(mnAltGato);
        mnGato.add(jSeparator9);

        mnRelCadGato.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mnRelCadGato.setForeground(new java.awt.Color(51, 51, 51));
        mnRelCadGato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/list.png"))); // NOI18N
        mnRelCadGato.setText("Consultar Gatos Cadastrados");
        mnGato.add(mnRelCadGato);

        mnAnimais.add(mnGato);

        barraMenu.add(mnAnimais);

        mnSair.setForeground(new java.awt.Color(84, 88, 113));
        mnSair.setText("Sair");
        mnSair.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        mnBtSair.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        mnBtSair.setForeground(new java.awt.Color(84, 88, 113));
        mnBtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/sair.png"))); // NOI18N
        mnBtSair.setText("Sair");
        mnBtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBtSairActionPerformed(evt);
            }
        });
        mnSair.add(mnBtSair);

        barraMenu.add(mnSair);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void mnBtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBtSairActionPerformed
        sair();
    }//GEN-LAST:event_mnBtSairActionPerformed
     public void sair (){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja sair do Menu Principal?", "Saida", JOptionPane.YES_NO_CANCEL_OPTION);
      if (resp == 0){
          dispose ();
          new Login().setVisible(true);
      }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuItem mnAltCao;
    private javax.swing.JMenuItem mnAltGato;
    private javax.swing.JMenu mnAnimais;
    private javax.swing.JMenuItem mnBtSair;
    private javax.swing.JMenuItem mnCadCao;
    private javax.swing.JMenuItem mnCadGato;
    private javax.swing.JMenu mnCao;
    private javax.swing.JMenu mnGato;
    private javax.swing.JMenuItem mnRelCadCao;
    private javax.swing.JMenuItem mnRelCadGato;
    private javax.swing.JMenu mnSair;
    // End of variables declaration//GEN-END:variables
}
